/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ventura
 */
public class MyFrame extends javax.swing.JFrame {

    public float subtotal;
    public float ivaCalculado;
    public final float IVA = 0.16f;
    public float total;
    
    public boolean ocupado=false;
    
    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
        buttonGroup1.add(chocolateRad);
        buttonGroup1.add(vainillaRad);
        buttonGroup1.add(fresaRad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chocolateRad = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        vainillaRad = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        fresaRad = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chispitasChocCheck = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        chispitasSabCheck = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cocoCheck = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        subtotalText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ivaText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        totalText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alan's Ice Creams");

        jLabel1.setFont(new java.awt.Font("Vijaya", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("Alan's IceCreams");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        chocolateRad.setText("Chocolate");
        jPanel1.add(chocolateRad);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("$15.00");
        jPanel1.add(jLabel2);

        vainillaRad.setText("Vainilla");
        jPanel1.add(vainillaRad);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("$10.00");
        jPanel1.add(jLabel3);

        fresaRad.setText("Fresa");
        jPanel1.add(fresaRad);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("$12.00");
        jPanel1.add(jLabel4);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 102)));
        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        chispitasChocCheck.setText("Chispitas de chocolate");
        jPanel2.add(chispitasChocCheck);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("$3.00");
        jPanel2.add(jLabel5);

        chispitasSabCheck.setText("Chispitas de sabores");
        jPanel2.add(chispitasSabCheck);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("$3.00");
        jPanel2.add(jLabel6);

        cocoCheck.setText("Coco");
        jPanel2.add(cocoCheck);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("$2.00");
        jPanel2.add(jLabel7);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 153)));
        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        jLabel8.setText("Subtotal");
        jPanel3.add(jLabel8);

        subtotalText.setEditable(false);
        subtotalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel3.add(subtotalText);

        jLabel9.setText("IVA");
        jPanel3.add(jLabel9);

        ivaText.setEditable(false);
        ivaText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel3.add(ivaText);

        jLabel10.setText("Total");
        jPanel3.add(jLabel10);

        totalText.setEditable(false);
        totalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel3.add(totalText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(ocupado==false)
        {
            if(chocolateRad.isSelected())
                subtotal = subtotal + 15;
            else if(vainillaRad.isSelected())
                subtotal = subtotal + 10;
            else if(fresaRad.isSelected())
                subtotal = subtotal + 12;

            if(chispitasChocCheck.isSelected())
                subtotal = subtotal + 3;

            if(chispitasSabCheck.isSelected())
                subtotal = subtotal + 3;

            if(cocoCheck.isSelected())
                subtotal = subtotal + 2;

            ivaCalculado = subtotal * IVA;

            total = subtotal + ivaCalculado;

            subtotalText.setText("$"+ (new Float(subtotal)).toString() );

            ivaText.setText("$" + ivaCalculado);

            totalText.setText("$" + total);
        
            ocupado = true;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        buttonGroup1.clearSelection();
        
        chispitasChocCheck.setSelected(false);
        chispitasSabCheck.setSelected(false);
        cocoCheck.setSelected(false);
        
        subtotalText.setText("");
        ivaText.setText("");
        totalText.setText("");
        
        subtotal = 0f;
        ivaCalculado = 0f;
        total = 0f;
        
        ocupado = false;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chispitasChocCheck;
    private javax.swing.JCheckBox chispitasSabCheck;
    private javax.swing.JRadioButton chocolateRad;
    private javax.swing.JCheckBox cocoCheck;
    private javax.swing.JRadioButton fresaRad;
    private javax.swing.JTextField ivaText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField subtotalText;
    private javax.swing.JTextField totalText;
    private javax.swing.JRadioButton vainillaRad;
    // End of variables declaration//GEN-END:variables
}
